//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobMeHomePage.JobPostServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkHours", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer")]
    [System.SerializableAttribute()]
    public partial class WorkHours : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobCategory", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer")]
    [System.SerializableAttribute()]
    public partial class JobCategory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobPost", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer")]
    [System.SerializableAttribute()]
    public partial class JobPost : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JobMeHomePage.JobPostServiceReference.Company companyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JobMeHomePage.JobPostServiceReference.JobCategory jobCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JobMeHomePage.JobPostServiceReference.WorkHours workHoursField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobTitle {
            get {
                return this.JobTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.JobTitleField, value) != true)) {
                    this.JobTitleField = value;
                    this.RaisePropertyChanged("JobTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JobMeHomePage.JobPostServiceReference.Company company {
            get {
                return this.companyField;
            }
            set {
                if ((object.ReferenceEquals(this.companyField, value) != true)) {
                    this.companyField = value;
                    this.RaisePropertyChanged("company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JobMeHomePage.JobPostServiceReference.JobCategory jobCategory {
            get {
                return this.jobCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.jobCategoryField, value) != true)) {
                    this.jobCategoryField = value;
                    this.RaisePropertyChanged("jobCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JobMeHomePage.JobPostServiceReference.WorkHours workHours {
            get {
                return this.workHoursField;
            }
            set {
                if ((object.ReferenceEquals(this.workHoursField, value) != true)) {
                    this.workHoursField = value;
                    this.RaisePropertyChanged("workHours");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Company", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer")]
    [System.SerializableAttribute()]
    public partial class Company : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BannerURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CVRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomepageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxRadiusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JobMeHomePage.JobPostServiceReference.BusinessType businessTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BannerURL {
            get {
                return this.BannerURLField;
            }
            set {
                if ((object.ReferenceEquals(this.BannerURLField, value) != true)) {
                    this.BannerURLField = value;
                    this.RaisePropertyChanged("BannerURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CVR {
            get {
                return this.CVRField;
            }
            set {
                if ((this.CVRField.Equals(value) != true)) {
                    this.CVRField = value;
                    this.RaisePropertyChanged("CVR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Homepage {
            get {
                return this.HomepageField;
            }
            set {
                if ((object.ReferenceEquals(this.HomepageField, value) != true)) {
                    this.HomepageField = value;
                    this.RaisePropertyChanged("Homepage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageURL {
            get {
                return this.ImageURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageURLField, value) != true)) {
                    this.ImageURLField = value;
                    this.RaisePropertyChanged("ImageURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxRadius {
            get {
                return this.MaxRadiusField;
            }
            set {
                if ((this.MaxRadiusField.Equals(value) != true)) {
                    this.MaxRadiusField = value;
                    this.RaisePropertyChanged("MaxRadius");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((this.PhoneField.Equals(value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JobMeHomePage.JobPostServiceReference.BusinessType businessType {
            get {
                return this.businessTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.businessTypeField, value) != true)) {
                    this.businessTypeField = value;
                    this.RaisePropertyChanged("businessType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessType", Namespace="http://schemas.datacontract.org/2004/07/ModelLayer")]
    [System.SerializableAttribute()]
    public partial class BusinessType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JobPostServiceReference.IJobPostService")]
    public interface IJobPostService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/CreateWorkHours", ReplyAction="http://tempuri.org/IJobPostService/CreateWorkHoursResponse")]
        void CreateWorkHours(JobMeHomePage.JobPostServiceReference.WorkHours obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/CreateWorkHours", ReplyAction="http://tempuri.org/IJobPostService/CreateWorkHoursResponse")]
        System.Threading.Tasks.Task CreateWorkHoursAsync(JobMeHomePage.JobPostServiceReference.WorkHours obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/DeleteWorkHours", ReplyAction="http://tempuri.org/IJobPostService/DeleteWorkHoursResponse")]
        void DeleteWorkHours(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/DeleteWorkHours", ReplyAction="http://tempuri.org/IJobPostService/DeleteWorkHoursResponse")]
        System.Threading.Tasks.Task DeleteWorkHoursAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/GetWorkHours", ReplyAction="http://tempuri.org/IJobPostService/GetWorkHoursResponse")]
        JobMeHomePage.JobPostServiceReference.WorkHours GetWorkHours(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/GetWorkHours", ReplyAction="http://tempuri.org/IJobPostService/GetWorkHoursResponse")]
        System.Threading.Tasks.Task<JobMeHomePage.JobPostServiceReference.WorkHours> GetWorkHoursAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/GetAllWorkHours", ReplyAction="http://tempuri.org/IJobPostService/GetAllWorkHoursResponse")]
        JobMeHomePage.JobPostServiceReference.WorkHours[] GetAllWorkHours();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/GetAllWorkHours", ReplyAction="http://tempuri.org/IJobPostService/GetAllWorkHoursResponse")]
        System.Threading.Tasks.Task<JobMeHomePage.JobPostServiceReference.WorkHours[]> GetAllWorkHoursAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/UpdateWorkHours", ReplyAction="http://tempuri.org/IJobPostService/UpdateWorkHoursResponse")]
        void UpdateWorkHours(JobMeHomePage.JobPostServiceReference.WorkHours obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/UpdateWorkHours", ReplyAction="http://tempuri.org/IJobPostService/UpdateWorkHoursResponse")]
        System.Threading.Tasks.Task UpdateWorkHoursAsync(JobMeHomePage.JobPostServiceReference.WorkHours obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/CreateJobCategory", ReplyAction="http://tempuri.org/IJobPostService/CreateJobCategoryResponse")]
        void CreateJobCategory(JobMeHomePage.JobPostServiceReference.JobCategory obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/CreateJobCategory", ReplyAction="http://tempuri.org/IJobPostService/CreateJobCategoryResponse")]
        System.Threading.Tasks.Task CreateJobCategoryAsync(JobMeHomePage.JobPostServiceReference.JobCategory obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/DeleteJobCategory", ReplyAction="http://tempuri.org/IJobPostService/DeleteJobCategoryResponse")]
        void DeleteJobCategory(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/DeleteJobCategory", ReplyAction="http://tempuri.org/IJobPostService/DeleteJobCategoryResponse")]
        System.Threading.Tasks.Task DeleteJobCategoryAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/GetJobCategory", ReplyAction="http://tempuri.org/IJobPostService/GetJobCategoryResponse")]
        JobMeHomePage.JobPostServiceReference.JobCategory GetJobCategory(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/GetJobCategory", ReplyAction="http://tempuri.org/IJobPostService/GetJobCategoryResponse")]
        System.Threading.Tasks.Task<JobMeHomePage.JobPostServiceReference.JobCategory> GetJobCategoryAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/GetAllJobCategories", ReplyAction="http://tempuri.org/IJobPostService/GetAllJobCategoriesResponse")]
        JobMeHomePage.JobPostServiceReference.JobCategory[] GetAllJobCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/GetAllJobCategories", ReplyAction="http://tempuri.org/IJobPostService/GetAllJobCategoriesResponse")]
        System.Threading.Tasks.Task<JobMeHomePage.JobPostServiceReference.JobCategory[]> GetAllJobCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/UpdateJobCategory", ReplyAction="http://tempuri.org/IJobPostService/UpdateJobCategoryResponse")]
        void UpdateJobCategory(JobMeHomePage.JobPostServiceReference.JobCategory obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/UpdateJobCategory", ReplyAction="http://tempuri.org/IJobPostService/UpdateJobCategoryResponse")]
        System.Threading.Tasks.Task UpdateJobCategoryAsync(JobMeHomePage.JobPostServiceReference.JobCategory obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/CreateJobPost", ReplyAction="http://tempuri.org/IJobPostService/CreateJobPostResponse")]
        void CreateJobPost(JobMeHomePage.JobPostServiceReference.JobPost obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/CreateJobPost", ReplyAction="http://tempuri.org/IJobPostService/CreateJobPostResponse")]
        System.Threading.Tasks.Task CreateJobPostAsync(JobMeHomePage.JobPostServiceReference.JobPost obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/DeleteJobPost", ReplyAction="http://tempuri.org/IJobPostService/DeleteJobPostResponse")]
        void DeleteJobPost(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/DeleteJobPost", ReplyAction="http://tempuri.org/IJobPostService/DeleteJobPostResponse")]
        System.Threading.Tasks.Task DeleteJobPostAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/GetJobPost", ReplyAction="http://tempuri.org/IJobPostService/GetJobPostResponse")]
        JobMeHomePage.JobPostServiceReference.JobPost GetJobPost(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/GetJobPost", ReplyAction="http://tempuri.org/IJobPostService/GetJobPostResponse")]
        System.Threading.Tasks.Task<JobMeHomePage.JobPostServiceReference.JobPost> GetJobPostAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/GetAllJobPost", ReplyAction="http://tempuri.org/IJobPostService/GetAllJobPostResponse")]
        JobMeHomePage.JobPostServiceReference.JobPost[] GetAllJobPost();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/GetAllJobPost", ReplyAction="http://tempuri.org/IJobPostService/GetAllJobPostResponse")]
        System.Threading.Tasks.Task<JobMeHomePage.JobPostServiceReference.JobPost[]> GetAllJobPostAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/UpdateJobPost", ReplyAction="http://tempuri.org/IJobPostService/UpdateJobPostResponse")]
        void UpdateJobPost(JobMeHomePage.JobPostServiceReference.JobPost obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobPostService/UpdateJobPost", ReplyAction="http://tempuri.org/IJobPostService/UpdateJobPostResponse")]
        System.Threading.Tasks.Task UpdateJobPostAsync(JobMeHomePage.JobPostServiceReference.JobPost obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJobPostServiceChannel : JobMeHomePage.JobPostServiceReference.IJobPostService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JobPostServiceClient : System.ServiceModel.ClientBase<JobMeHomePage.JobPostServiceReference.IJobPostService>, JobMeHomePage.JobPostServiceReference.IJobPostService {
        
        public JobPostServiceClient() {
        }
        
        public JobPostServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JobPostServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobPostServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobPostServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateWorkHours(JobMeHomePage.JobPostServiceReference.WorkHours obj) {
            base.Channel.CreateWorkHours(obj);
        }
        
        public System.Threading.Tasks.Task CreateWorkHoursAsync(JobMeHomePage.JobPostServiceReference.WorkHours obj) {
            return base.Channel.CreateWorkHoursAsync(obj);
        }
        
        public void DeleteWorkHours(int id) {
            base.Channel.DeleteWorkHours(id);
        }
        
        public System.Threading.Tasks.Task DeleteWorkHoursAsync(int id) {
            return base.Channel.DeleteWorkHoursAsync(id);
        }
        
        public JobMeHomePage.JobPostServiceReference.WorkHours GetWorkHours(int id) {
            return base.Channel.GetWorkHours(id);
        }
        
        public System.Threading.Tasks.Task<JobMeHomePage.JobPostServiceReference.WorkHours> GetWorkHoursAsync(int id) {
            return base.Channel.GetWorkHoursAsync(id);
        }
        
        public JobMeHomePage.JobPostServiceReference.WorkHours[] GetAllWorkHours() {
            return base.Channel.GetAllWorkHours();
        }
        
        public System.Threading.Tasks.Task<JobMeHomePage.JobPostServiceReference.WorkHours[]> GetAllWorkHoursAsync() {
            return base.Channel.GetAllWorkHoursAsync();
        }
        
        public void UpdateWorkHours(JobMeHomePage.JobPostServiceReference.WorkHours obj) {
            base.Channel.UpdateWorkHours(obj);
        }
        
        public System.Threading.Tasks.Task UpdateWorkHoursAsync(JobMeHomePage.JobPostServiceReference.WorkHours obj) {
            return base.Channel.UpdateWorkHoursAsync(obj);
        }
        
        public void CreateJobCategory(JobMeHomePage.JobPostServiceReference.JobCategory obj) {
            base.Channel.CreateJobCategory(obj);
        }
        
        public System.Threading.Tasks.Task CreateJobCategoryAsync(JobMeHomePage.JobPostServiceReference.JobCategory obj) {
            return base.Channel.CreateJobCategoryAsync(obj);
        }
        
        public void DeleteJobCategory(int id) {
            base.Channel.DeleteJobCategory(id);
        }
        
        public System.Threading.Tasks.Task DeleteJobCategoryAsync(int id) {
            return base.Channel.DeleteJobCategoryAsync(id);
        }
        
        public JobMeHomePage.JobPostServiceReference.JobCategory GetJobCategory(int id) {
            return base.Channel.GetJobCategory(id);
        }
        
        public System.Threading.Tasks.Task<JobMeHomePage.JobPostServiceReference.JobCategory> GetJobCategoryAsync(int id) {
            return base.Channel.GetJobCategoryAsync(id);
        }
        
        public JobMeHomePage.JobPostServiceReference.JobCategory[] GetAllJobCategories() {
            return base.Channel.GetAllJobCategories();
        }
        
        public System.Threading.Tasks.Task<JobMeHomePage.JobPostServiceReference.JobCategory[]> GetAllJobCategoriesAsync() {
            return base.Channel.GetAllJobCategoriesAsync();
        }
        
        public void UpdateJobCategory(JobMeHomePage.JobPostServiceReference.JobCategory obj) {
            base.Channel.UpdateJobCategory(obj);
        }
        
        public System.Threading.Tasks.Task UpdateJobCategoryAsync(JobMeHomePage.JobPostServiceReference.JobCategory obj) {
            return base.Channel.UpdateJobCategoryAsync(obj);
        }
        
        public void CreateJobPost(JobMeHomePage.JobPostServiceReference.JobPost obj) {
            base.Channel.CreateJobPost(obj);
        }
        
        public System.Threading.Tasks.Task CreateJobPostAsync(JobMeHomePage.JobPostServiceReference.JobPost obj) {
            return base.Channel.CreateJobPostAsync(obj);
        }
        
        public void DeleteJobPost(int id) {
            base.Channel.DeleteJobPost(id);
        }
        
        public System.Threading.Tasks.Task DeleteJobPostAsync(int id) {
            return base.Channel.DeleteJobPostAsync(id);
        }
        
        public JobMeHomePage.JobPostServiceReference.JobPost GetJobPost(int id) {
            return base.Channel.GetJobPost(id);
        }
        
        public System.Threading.Tasks.Task<JobMeHomePage.JobPostServiceReference.JobPost> GetJobPostAsync(int id) {
            return base.Channel.GetJobPostAsync(id);
        }
        
        public JobMeHomePage.JobPostServiceReference.JobPost[] GetAllJobPost() {
            return base.Channel.GetAllJobPost();
        }
        
        public System.Threading.Tasks.Task<JobMeHomePage.JobPostServiceReference.JobPost[]> GetAllJobPostAsync() {
            return base.Channel.GetAllJobPostAsync();
        }
        
        public void UpdateJobPost(JobMeHomePage.JobPostServiceReference.JobPost obj) {
            base.Channel.UpdateJobPost(obj);
        }
        
        public System.Threading.Tasks.Task UpdateJobPostAsync(JobMeHomePage.JobPostServiceReference.JobPost obj) {
            return base.Channel.UpdateJobPostAsync(obj);
        }
    }
}
